title: Haichao Zhang
description: Research notes and results in machine learning, robotics and AI.
url: "https://haichao-zhang.github.io"
permalink: /:year/:month/:day/:title/
timezone: America/Los_Angeles
